ignoreUser:
  - matt-riley
isGraphQL: true
schemaCheck:
  paths:
    - path: schema.graphql
      mainBranch: master
  rules:
    - FIELD_CHANGED_KIND
    - FIELD_REMOVED
    - TYPE_REMOVED
    - ARG_REMOVED
    - ARG_CHANGED_KIND
    - MISSING_FIELD_DESCRIPTION
    - MISSING_TYPE_DESCRIPTION
